# Site settings
# title:          Tale
# description:    "Minimal Jekyll theme for storytellers"
# baseurl:        "/tale"
# url:            "https://chesterhow.github.io"

title:          YeonJun Rhee
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/"
url:            "https://yeonjunrhee.github.io"

# Author
author:
  name:         yeonjunrhee
  url:          https://harmajun.com
  email:        harmattans@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
